name: sticky_header_list
description: Sticky headers list
version: 1.0.0
author: Josip Krnjic
homepage: https://github.com/itsJoKr/sticky_header_list

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

